### PR TITLE
feat: Encapsulate hardware-specific operations

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by jserv** [comment]
Reworking is required.

**Comment by splasky** [comment]
I would do this later.

**Comment by splasky** [comment]
@HowJMay code review is required.

**Comment by jserv** [comment]
> Done. @HowJMay code review is required.

Don't say "Done." Use GitHub functionality to specify reviewer(s).

**Comment by howjmay** [comment]
Transfer this PR to @splasky. He will keep working on this PR.

**Pull request closed without merging**
