### PR TITLE
Bump copyright date for each source

### LINKED ISSUE #38: Bump copyright date
Copyright date of modified files should be bumped.

### PR DESCRIPTION
**Pull request by splasky**
Update copyright from 2019 to 2019-2020.
Add copyright license if it wasn't included in header file.

close #38

### CODE REVIEW

**Comment by jserv** [comment]
Use precise wording. Modify git commit messages.

**Review by howjmay — CHANGES_REQUESTED** [review]
add description `closes #38`

**Comment by HowJMay** [comment]
fix grammar error `Add copyright if header didn't include.` to `Add copyright license if it wasn't included in header file.`

**Review by howjmay — CHANGES_REQUESTED** [review]
fix grammar error `Add copyright if header didn't include.` to `Add copyright license if it wasn't included in header file`.

**Review by howjmay — APPROVED** [review]

**Pull request merged**
